application: spellingbeehelper
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /urlexists
  script: urlexists.app

- url: /wordlist/.*
  script: word-list.app

- url: /word/.*
  script: word.app

- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html

- url: /
  static_dir: static

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
