application: spellingbeehelper
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html

- url: /
  static_dir: static
